# api/schemas/models.py
#
# PURPOSE:
#   Defines the Pydantic models (schemas) for all API request bodies
#   and response bodies in the FINSIGHT_GraphRAG FastAPI application.
#
# WHAT ARE PYDANTIC MODELS?
#   Pydantic models are Python classes that define the expected shape
#   of data. When FastAPI receives a request, it automatically:
#     1. Parses the incoming JSON into the Pydantic model
#     2. Validates that all required fields are present
#     3. Validates that field types are correct
#     4. Returns a clear 422 error to the caller if validation fails
#   When FastAPI sends a response, Pydantic serialises the model to JSON.
#
# WHY DEFINE THESE SEPARATELY?
#   Keeping schemas in one file means:
#     - All API contracts are visible in one place
#     - Route files stay clean — they only contain business logic
#     - If the API shape changes, there is one file to update
#     - Students reading the code understand the API shape immediately
#       without reading through route handler logic
#
# DO YOU RUN THIS FILE?
#   No. Imported by api/routes/query.py, api/routes/ingest.py,
#   api/routes/health.py, and api/main.py.


from pydantic import BaseModel, Field     # base class and field descriptor
from typing import List, Optional         # type hints
from datetime import datetime             # for timestamp fields


# =============================================================================
# QUERY ENDPOINT — POST /query
# =============================================================================

class QueryRequest(BaseModel):
    """
    Request body for the POST /query endpoint.

    The caller sends a JSON body with at least a "question" field.
    The optional fields allow the caller to override pipeline defaults
    for specific queries without changing the .env configuration.

    Example request body:
        {
            "question": "How does Taiwan risk affect Apple revenue?",
            "top_k_vector": 5,
            "top_k_graph_hops": 3
        }
    """

    # The user's question — required, no default
    # min_length=10 prevents trivially short questions that would produce
    # meaningless results and waste OpenAI API credits
    question: str = Field(
        ...,
        min_length=10,
        description="The financial intelligence question to answer",
        example="If ASML stops shipping EUV machines, which companies face the highest revenue risk?"
    )

    # Optional override for number of ChromaDB chunks to retrieve
    # If not provided, uses TOP_K_VECTOR from .env (default 5)
    top_k_vector: Optional[int] = Field(
        default=None,
        ge=1,           # must be at least 1
        le=20,          # cap at 20 to prevent context window overflow
        description="Number of text chunks to retrieve from ChromaDB. Overrides .env setting."
    )

    # Optional override for Neo4j graph traversal depth
    # If not provided, entity_agent decides based on query complexity
    top_k_graph_hops: Optional[int] = Field(
        default=None,
        ge=1,           # must be at least 1
        le=5,           # cap at 5 — deeper traversals are very slow
        description="Maximum graph traversal hops in Neo4j. Overrides entity_agent recommendation."
    )


class QueryResponse(BaseModel):
    """
    Response body for the POST /query endpoint.

    Contains the final answer, supporting evidence metadata, and
    pipeline execution details. The caller can use sources and
    graph_paths_used to verify the answer against source documents.

    Example response body:
        {
            "question": "If ASML stops shipping EUV machines...",
            "answer": "ASML export restrictions would directly impact TSMC...",
            "sources": ["asml_technology_report_FY2023.pdf", ...],
            "graph_paths_used": ["ASML -[SUPPLIES_TO]-> TSMC", ...],
            "intent_detected": "risk_cascade",
            "entities_found": ["ASML", "TSMC", "Apple", "Nvidia"],
            "success": true,
            "error": null
        }
    """

    # The original question echoed back for context
    question: str = Field(description="The original question asked")

    # The complete answer generated by the synthesis agent
    answer: str = Field(description="The generated answer from GPT-4o")

    # List of PDF filenames cited as evidence in the answer
    sources: List[str] = Field(
        default_factory=list,
        description="Source PDF documents referenced in the answer"
    )

    # The graph relationship chains that contributed to the answer
    # Included for explainability — shows the multi-hop reasoning path
    graph_paths_used: List[str] = Field(
        default_factory=list,
        description="Graph relationship paths used in reasoning"
    )

    # The query intent detected by entity_agent
    # One of: risk_cascade, supply_chain, financial, competitive, general
    intent_detected: Optional[str] = Field(
        default=None,
        description="Query intent detected by entity_agent"
    )

    # Entity names extracted from the question
    entities_found: List[str] = Field(
        default_factory=list,
        description="Entities extracted from the question"
    )

    # Whether the pipeline completed without errors
    success: bool = Field(
        default=True,
        description="True if the pipeline completed successfully"
    )

    # Error message if the pipeline failed — None if success=True
    error: Optional[str] = Field(
        default=None,
        description="Error message if pipeline failed, null otherwise"
    )


# =============================================================================
# INGEST ENDPOINT — POST /ingest
# =============================================================================

class IngestRequest(BaseModel):
    """
    Request body for the POST /ingest endpoint.

    Triggers the full ingestion pipeline:
      PDF files -> text chunks -> Neo4j graph + ChromaDB index

    The caller can optionally override the PDF directory and control
    whether existing graph data should be cleared before re-ingesting.

    Example request body:
        {
            "pdf_dir": "./data/pdfs",
            "clear_existing": true
        }
    """

    # Path to the folder containing PDF files to ingest
    # Defaults to the PDF_DIR value from .env
    pdf_dir: Optional[str] = Field(
        default=None,
        description="Path to PDF directory. Defaults to PDF_DIR from .env."
    )

    # Whether to clear existing Neo4j and ChromaDB data before ingesting
    # Set to True when re-running ingestion from scratch
    # Set to False to add new documents to an existing graph
    clear_existing: bool = Field(
        default=False,
        description="If true, clears existing Neo4j graph and ChromaDB index before ingesting"
    )


class IngestResponse(BaseModel):
    """
    Response body for the POST /ingest endpoint.

    Returns a summary of what was ingested — how many PDFs were processed,
    how many chunks were created, how many entities and relationships were
    written to Neo4j, and how many chunks were indexed in ChromaDB.

    Example response body:
        {
            "success": true,
            "message": "Ingestion complete",
            "pdfs_processed": 5,
            "chunks_created": 94,
            "entities_extracted": 52,
            "relationships_extracted": 38,
            "nodes_written_to_neo4j": 52,
            "relationships_written_to_neo4j": 36,
            "chunks_indexed_in_chromadb": 94,
            "error": null
        }
    """

    success: bool = Field(description="True if ingestion completed successfully")

    message: str = Field(description="Human-readable status message")

    # Counts for each stage of the pipeline
    pdfs_processed:   int = Field(default=0, description="Number of PDF files processed")
    chunks_created:   int = Field(default=0, description="Number of text chunks created")
    entities_extracted: int = Field(default=0, description="Unique entities extracted by GPT-4o")
    relationships_extracted: int = Field(default=0, description="Unique relationships extracted by GPT-4o")
    nodes_written_to_neo4j: int = Field(default=0, description="Nodes written to Neo4j AuraDB")
    relationships_written_to_neo4j: int = Field(default=0, description="Relationships written to Neo4j AuraDB")
    chunks_indexed_in_chromadb: int = Field(default=0, description="Chunks indexed in ChromaDB")

    error: Optional[str] = Field(
        default=None,
        description="Error message if ingestion failed, null otherwise"
    )


# =============================================================================
# HEALTH ENDPOINT — GET /health
# =============================================================================

class Neo4jHealth(BaseModel):
    """
    Health status of the Neo4j AuraDB connection.
    Nested inside HealthResponse.
    """

    status: str = Field(description="'healthy' or 'unhealthy'")
    node_count: int = Field(default=0, description="Total nodes in the graph")
    relationship_count: int = Field(default=0, description="Total relationships in the graph")
    message: str = Field(description="Human-readable status detail")


class ChromaDBHealth(BaseModel):
    """
    Health status of the ChromaDB vector store.
    Nested inside HealthResponse.
    """

    status: str = Field(description="'healthy' or 'unhealthy'")
    document_count: int = Field(default=0, description="Total chunks indexed in ChromaDB")
    persist_dir: str = Field(description="Path where ChromaDB index is stored on disk")
    message: str = Field(description="Human-readable status detail")


class HealthResponse(BaseModel):
    """
    Response body for the GET /health endpoint.

    Returns the overall system health plus the individual health
    of each component. The caller can use this to confirm the
    pipeline is ready to accept queries before running the demo.

    Example response body:
        {
            "status": "healthy",
            "neo4j": {
                "status": "healthy",
                "node_count": 52,
                "relationship_count": 38,
                "message": "Neo4j is running. 52 nodes, 38 relationships."
            },
            "chromadb": {
                "status": "healthy",
                "document_count": 94,
                "persist_dir": "./data/chroma_db",
                "message": "ChromaDB is healthy. 94 chunks indexed."
            },
            "pipeline_ready": true,
            "timestamp": "2024-11-01T10:30:00"
        }
    """

    # Overall system status — "healthy" only if ALL components are healthy
    status: str = Field(description="Overall system health: 'healthy' or 'degraded'")

    # Individual component health
    neo4j:    Neo4jHealth    = Field(description="Neo4j AuraDB health details")
    chromadb: ChromaDBHealth = Field(description="ChromaDB vector store health details")

    # True only if both Neo4j and ChromaDB are healthy AND contain data
    # If this is False, queries will fail or return poor results
    pipeline_ready: bool = Field(
        description="True if pipeline has been ingested and is ready for queries"
    )

    # UTC timestamp of when this health check was performed
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="UTC timestamp of health check"
    )