# api/main.py
#
# PURPOSE:
#   The FastAPI application entry point.
#   Creates the FastAPI app, registers all three routers,
#   configures CORS, and handles application startup/shutdown.
#
# HOW TO START THE SERVER:
#   From your project root folder (FINSIGHT_GraphRAG/) with venv activated:
#
#     uvicorn api.main:app --reload --host 0.0.0.0 --port 8000
#
#   --reload  : auto-restarts when you change any .py file (dev mode)
#   --host    : 0.0.0.0 makes it accessible from any network interface
#   --port    : 8000 is the standard port for local FastAPI development
#
# ONCE RUNNING, THREE ENDPOINTS ARE AVAILABLE:
#   GET  http://localhost:8000/health     -- check pipeline is ready
#   POST http://localhost:8000/ingest     -- run ingestion pipeline
#   POST http://localhost:8000/query      -- ask a question
#
# INTERACTIVE API DOCS (auto-generated by FastAPI):
#   http://localhost:8000/docs            -- Swagger UI (try endpoints in browser)
#   http://localhost:8000/redoc           -- ReDoc UI (clean documentation view)
#
# DO YOU RUN THIS FILE DIRECTLY?
#   No. Start it with uvicorn as shown above.
#   Never run:  python api/main.py
#   Always run: uvicorn api.main:app --reload


from contextlib import asynccontextmanager  # manages startup/shutdown lifecycle
from fastapi import FastAPI                 # the web framework
from fastapi.middleware.cors import CORSMiddleware
# CORSMiddleware allows browser-based clients (e.g. a React frontend)
# to call this API. Without CORS, browsers block cross-origin requests.

from loguru import logger                   # structured logging

from api.routes.health import health_router
from api.routes.ingest import ingest_router
from api.routes.query  import query_router
# All three routers imported so we can mount them onto the app


# -----------------------------------------------------------------------------
# LIFESPAN HANDLER
# -----------------------------------------------------------------------------
# The lifespan context manager runs code at application startup and shutdown.
# Code before `yield` runs when uvicorn starts the server.
# Code after `yield` runs when uvicorn shuts down the server.
#
# We use this to:
#   - Log a startup banner so you can confirm all config loaded correctly
#   - Verify that the .env file was read successfully
#   - Log a clean shutdown message

@asynccontextmanager
async def lifespan(app: FastAPI):
    """
    Handles application startup and shutdown events.

    Startup: logs a banner confirming the server is running and shows
             key configuration values so you can verify .env was loaded.
    Shutdown: logs a clean shutdown message.
    """

    # --- STARTUP ---
    # Import settings here to confirm .env loaded without errors
    # If settings import fails, the server will not start and the error
    # is shown immediately — much better than a silent misconfiguration
    from graph_rag.utils.config import settings

    logger.info("=" * 60)
    logger.info("FINSIGHT_GraphRAG API starting up")
    logger.info("=" * 60)
    logger.info(f"LLM model:         {settings.llm_model}")
    logger.info(f"Embedding model:   {settings.embedding_model}")
    logger.info(f"Neo4j URI:         {settings.neo4j_uri}")
    logger.info(f"ChromaDB dir:      {settings.chroma_persist_dir}")
    logger.info(f"PDF directory:     {settings.pdf_dir}")
    logger.info(f"Chunk size:        {settings.chunk_size}")
    logger.info(f"Top K vector:      {settings.top_k_vector}")
    logger.info(f"Top K graph hops:  {settings.top_k_graph_hops}")
    logger.info("=" * 60)
    logger.info("API docs available at: http://localhost:8000/docs")
    logger.info("Health check at:       http://localhost:8000/health")
    logger.info("=" * 60)

    # Yield control to FastAPI — the server runs while we are yielded
    yield

    # --- SHUTDOWN ---
    logger.info("FINSIGHT_GraphRAG API shutting down. Goodbye.")


# -----------------------------------------------------------------------------
# FASTAPI APP INSTANCE
# -----------------------------------------------------------------------------

app = FastAPI(
    title="FINSIGHT_GraphRAG API",
    description=(
        "A Graph RAG pipeline for financial supply chain intelligence. "
        "Combines Neo4j knowledge graph traversal with ChromaDB vector search "
        "to answer complex multi-hop questions about semiconductor supply chains. "
        "Built with LangGraph, LangChain, and GPT-4o."
    ),
    version="1.0.0",

    # Contact info shown in the auto-generated API docs
    contact={
        "name":  "Tarka Upskilling",
        "url":   "https://tarkaupskilling.com",
        "email": "chirantan@tarkaupskilling.com",
    },

    # The lifespan handler defined above
    lifespan=lifespan,
)


# -----------------------------------------------------------------------------
# CORS MIDDLEWARE
# -----------------------------------------------------------------------------
# CORS (Cross-Origin Resource Sharing) controls which domains can call
# this API from a browser. Setting allow_origins=["*"] allows any domain.
# This is fine for a local development and demo environment.
# For production, replace "*" with your specific frontend domain.

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],       # allow all origins (dev/demo setting)
    allow_credentials=True,    # allow cookies and auth headers
    allow_methods=["*"],       # allow all HTTP methods (GET, POST, etc.)
    allow_headers=["*"],       # allow all request headers
)


# -----------------------------------------------------------------------------
# REGISTER ROUTERS
# -----------------------------------------------------------------------------
# include_router() mounts each router onto the app.
# Each router has its own prefix defined inside its own file:
#   health_router -> prefix="/health"  -> GET  /health
#   ingest_router -> prefix="/ingest"  -> POST /ingest
#   query_router  -> prefix="/query"   -> POST /query

app.include_router(health_router)
app.include_router(ingest_router)
app.include_router(query_router)


# -----------------------------------------------------------------------------
# ROOT ENDPOINT
# -----------------------------------------------------------------------------

@app.get("/", tags=["root"])
def root():
    """
    Root endpoint — confirms the server is running.
    Returns a welcome message with links to the main endpoints.
    """
    return {
        "message":    "FINSIGHT_GraphRAG API is running.",
        "docs":       "http://localhost:8000/docs",
        "health":     "http://localhost:8000/health",
        "ingest":     "POST http://localhost:8000/ingest",
        "query":      "POST http://localhost:8000/query",
        "version":    "1.0.0",
    }